language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- nightly
- pypy3
matrix:
  allow_failures:
  - python: nightly
  - python: pypy3
before_script:
- pip install -r requirements-dev.txt
- pip install .
- python3 -c 'import networkx as nx; nx.write_weighted_edgelist(nx.karate_club_graph(), "karate_club.tsv", delimiter="\t")'
script:
- mypy --ignore-missing-imports .
- python3 -munittest discover
- python3 -mchinese_whispers karate_club.tsv
- chinese-whispers karate_club.tsv
